apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.large
    desiredCapacity: 2
    volumeSize: 8
    ssh:
      publicKeyPath: ~/.ssh/id_ed25519.pub
